development:
    database: syndicate_dev 
    adapter: mysql 
    hostname: localhost 
    username: root 
    password:
      
test:
    database: syndicate_test
    adapter: mysql
    hostname: localhost
    username: root
    password:
    pool: 5
    
# production:
#   adapter:   mysql
#   database:  audi_ims_production
#   username:  deploy
#   password:  sgb5wI4G5l
#   host:      ec2-174-129-147-0.compute-1.amazonaws.com
#   pool:      15
