# must be mysql

development:
    database: syndicate_dev 
    adapter: jdbcmysql  
    hostname: localhost 
    username: root 
    password:
      
test:
    database: syndicate_test
    adapter: jdbcmysql
    hostname: localhost
    username: root
    password:
    pool: 5
