# must be mysql

development:
    database: syndicate_dev 
    adapter: mysql  
    hostname: localhost 
    username: root 
    password:
      
test:
    database: syndicate_test
    adapter: mysql
    hostname: localhost
    username: root
    password:
    pool: 5
